# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 338)
        self.numberone = QtWidgets.QLineEdit(Dialog)
        self.numberone.setGeometry(QtCore.QRect(60, 180, 113, 20))
        self.numberone.setObjectName("numberone")
        self.number_2 = QtWidgets.QLineEdit(Dialog)
        self.number_2.setGeometry(QtCore.QRect(230, 180, 113, 20))
        self.number_2.setObjectName("number_2")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(170, 220, 61, 31))
        self.addButton.setObjectName("addButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 130, 91, 41))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pic = QtWidgets.QLabel(Dialog)
        self.pic.setGeometry(QtCore.QRect(20, 20, 111, 101))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("cute.jpg"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(200, 40, 51, 21))
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(200, 60, 51, 41))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(260, 30, 121, 41))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(260, 60, 121, 41))
        self.radioButton_4.setObjectName("radioButton_4")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(260, 10, 91, 31))
        self.checkBox.setObjectName("checkBox")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(310, 110, 61, 31))
        self.comboBox.setObjectName("comboBox")
        self.language = QtWidgets.QLabel(Dialog)
        self.language.setGeometry(QtCore.QRect(150, 100, 91, 41))
        self.language.setStyleSheet("\n"
"\n"
"font: 63 10pt \"Sitka Display Semibold\";")
        self.language.setAlignment(QtCore.Qt.AlignCenter)
        self.language.setObjectName("language")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(260, 280, 131, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(270, 250, 91, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addButton.setText(_translate("Dialog", "caculate"))
        self.label.setText(_translate("Dialog", "result"))
        self.radioButton.setText(_translate("Dialog", "加"))
        self.radioButton_2.setText(_translate("Dialog", "減"))
        self.radioButton_3.setText(_translate("Dialog", "乘"))
        self.radioButton_4.setText(_translate("Dialog", "除"))
        self.checkBox.setText(_translate("Dialog", "CheckBox"))
        self.language.setText(_translate("Dialog", "Answer is..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
