# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(208, 215, 255);")
        self.helloButton = QtWidgets.QPushButton(Dialog)
        self.helloButton.setGeometry(QtCore.QRect(100, 170, 101, 31))
        self.helloButton.setStyleSheet("font: 11pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(130, 135, 139);\n"
"")
        self.helloButton.setObjectName("helloButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(160, 130, 113, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit.setObjectName("lineEdit")
        self.pressmeButton_2 = QtWidgets.QPushButton(Dialog)
        self.pressmeButton_2.setGeometry(QtCore.QRect(250, 170, 81, 31))
        self.pressmeButton_2.setStyleSheet("font: 11pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(130, 135, 139);\n"
"")
        self.pressmeButton_2.setObjectName("pressmeButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 70, 151, 51))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pic = QtWidgets.QLabel(Dialog)
        self.pic.setGeometry(QtCore.QRect(20, 20, 101, 91))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("1result.jpg"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "hello"))
        self.helloButton.setText(_translate("Dialog", "show string"))
        self.pressmeButton_2.setText(_translate("Dialog", "Press"))
        self.label.setText(_translate("Dialog", "please enter value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
